---
- name: etcd
  hosts: ccma
  gather_facts: no

  vars:
    ansible_become_pass: "ccma"

  tasks:
    - name: Install Python 2.7
      become: yes
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

    - name: Gather facts after Python is definitely present
      become: yes
      setup:

    - name: Install pip and docker.io
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python-pip
          - docker.io

    - name: Install Docker Python library
      become: yes
      pip:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker

    - name: Add ccma to the docker group
      become: yes
      shell: usermod -aG docker ccma
      register: ccma_to_docker

    - name: Reboot immediately if there was a change
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: ccma_to_docker is changed

    - name: Wait for the reboot to complete if there was a change
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: ccma_to_docker is changed

    - name: Install pexpect
      become: yes
      pip:
        name: pexpect

    - name: Stop Docker engine
      become: yes
      expect:
        command: "service docker stop"
        responses:
          (?i)password: "ccma"

    - name: Restart Docker engine with cluster configuration
      become: yes
      shell: "{{ item }}"
      with_items:
        - "nohup /usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --cluster-store=etcd://{{ ansible_default_ipv4.address }}:2379 --cluster-advertise={{ ansible_default_ipv4.address }}:2375 >/dev/null 2>&1 &"


    - name: Create a directory for mounting host volume
      file:
        path: /home/ccma/etcd
        state: directory
        owner: ccma
        group: ccma
        mode: 0755

    - name: Check for containers that actually exist
      shell: 'docker ps -aq --filter "name={{ item }}"'
      with_items:
        - etcd
      register: found_containers

    - name: Remove the containers found by the above command
      shell: 'docker stop {{ item.item }} && docker rm -fv {{ item.item }}'
      with_items: '{{ found_containers.results }}'
      when: item.stdout

    - name: Debug
      debug:
        var: hostvars[inventory_hostname]['etcd_name']

    - name: Run a 3 node etcd cluster
      docker_container:
        image: gcr.io/etcd-development/etcd:latest
        name: etcd
        volumes:
          - /home/ccma/etcd:/etcd-data
        ports:
          - "2379:2379"
          - "2380:2380"
        command: [
            "/usr/local/bin/etcd",
            "--data-dir=/etcd-data",
            "--name {{ hostvars[inventory_hostname]['etcd_name'] }}",
            "--initial-advertise-peer-urls http://{{ ansible_default_ipv4.address }}:2380",
            "--listen-peer-urls http://0.0.0.0:2380",
            "--advertise-client-urls http://{{ ansible_default_ipv4.address }}:2379",
            "--listen-client-urls http://0.0.0.0:2379",
            "--initial-cluster {{ cluster }}",
            "--initial-cluster-state {{ cluster_state }}",
            "--initial-cluster-token {{ token }}"
          ]
      vars:
        cluster: "etcd1=http://10.236.1.1:2380,etcd2=http://10.236.1.2:2380,etcd3=http://10.236.1.3:2380"
        cluster_state: "new"
        token: "etcd-cluster"
      register: run_etcd_cluster

    - name: Debug run_etcd_cluster
      debug:
        var: run_etcd_cluster


- name: etcd1
  hosts: etcd1
  gather_facts: no

  vars:
    ansible_become_pass: "ccma"

  tasks:
    - name: Delete a network, disconnecting all containers
      docker_network:
        name: network_etcd
        state: absent
        force: yes

    - name: Create a network
      become: yes
      shell: "docker network create -d overlay network_etcd"
